instrumentation:
    extensions:
        - .js
        - .jsx
    excludes:
        - 'server.js'
        - 'webpack.config.js'
        - 'devops/**'
        - 'node_modules/**'
        - 'test/**'
        - '.vscode/**'
        - 'build/**'
    include-all-sources: true
    es-modules: true
check:
    global:
        statements: 100
        lines: 100
        branches: 100
        functions: 100

